Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 199

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Documentation:
    Enabled: false

AllCops:
  Exclude:
    - "config/**"
    - "app/channels/application_cable/connection.rb"
    - "app/channels/application_cable/channel.rb"
