Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 199

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Documentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: always_ignore

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/GuardClause:
  MinBodyLength: 5

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/DoubleNegation:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

AllCops:
  Exclude:
    - "config/**/*"
    - "app/channels/application_cable/connection.rb"
    - "app/channels/application_cable/channel.rb"
    - "bin/**/*"
    - "db/**/*"
